version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  client:
    build: 
      context: ./client/frontend
      args:
        - VITE_API_URL=http://localhost:5000/api
    ports:
      - "3000:80"
